//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group12_iCLOTHINGAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUTUS
    {
        public string COMPNAME { get; set; }
        public string SHIPPPOLICY { get; set; }
        public string RETURNPOL { get; set; }
        public string CONTACTINFO { get; set; }
        public string ABDESCRIPTION { get; set; }
        public string ADMINID { get; set; }
    
        public virtual ADMINISTRATOR ADMINISTRATOR { get; set; }
    }
}
