//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group12_iCLOTHINGAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        public string EMAILNO { get; set; }
        public Nullable<System.DateTime> EMAILDATE { get; set; }
        public string EMAILSUB { get; set; }
        public string EMAILBODY { get; set; }
        public string USERID { get; set; }
        public string ADMINID { get; set; }
    
        public virtual ADMINISTRATOR ADMINISTRATOR { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
