//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group12_iCLOTHINGAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group12_iCLOTHINGDBEntities2 : DbContext
    {
        public Group12_iCLOTHINGDBEntities2()
            : base("name=Group12_iCLOTHINGDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABOUTUS> ABOUTUS { get; set; }
        public virtual DbSet<ADMINISTRATOR> ADMINISTRATOR { get; set; }
        public virtual DbSet<BRAND> BRAND { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<EMAIL> EMAIL { get; set; }
        public virtual DbSet<ITEMDELIVERY> ITEMDELIVERY { get; set; }
        public virtual DbSet<ORDERSTATUS> ORDERSTATUS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<SHOPPINGCART> SHOPPINGCART { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USERCOMMENTS> USERCOMMENTS { get; set; }
        public virtual DbSet<USERPASSWORD> USERPASSWORD { get; set; }
        public virtual DbSet<USERQUERY> USERQUERY { get; set; }
    }
}
