//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group12_iCLOTHINGAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERCOMMENTS
    {
        public string COMMENTNO { get; set; }
        public Nullable<System.DateTime> COMMENTDATE { get; set; }
        public string COMMDESCRIPTION { get; set; }
        public string CUSTID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
