//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group12_iCLOTHINGAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERPASSWORD
    {
        public string USERID { get; set; }
        public string ACCNAME { get; set; }
        public string ENCRYPTPASS { get; set; }
        public Nullable<int> PASSEXPIRYTIME { get; set; }
        public Nullable<System.DateTime> ACCEXPITYDATE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
